version: "3.9"
services:
  code:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "4.12.0"
        CODESERVER_VERSION: "4.12.0"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "code:dev"
    image: "gautada/code:dev"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: "code"
    ports:
      - "3306:3306"
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/code/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/code/backup-volume
      
