version: "3.9"
services:
  vscode:
    build:
      args:
        ALPINE_VERSION: "3.16.5"
        CONTAINER_VERSION: "0.0.0"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "vscode:dev"
    image: "gautada/vscode:dev"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: "vscode"
    ports:
      - "3306:3306"
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/vscode/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/vscode/backup-volume
      
