#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

app_version() {
 /usr/local/bin/code-server --version |  awk -F ' ' '{print $1}'
}

app_entrypoint() {
 /bin/mkdir -p /mnt/volumes/container/users /mnt/volumes/container/extensions
 /usr/local/bin/code-server --app-name code.gautier.org \
                            --bind-addr 0.0.0.0:8080 \
                            --config /etc/container/code-server.config \ 
                            --user-data-dir /mnt/volumes/container/users \
                            --extensions-dir /mnt/volumes/container/extensions
}
